keys:
  - &admin_macbook_m1 age169v95f5fqx0sg5mjpp63sumrj9sma9se203ra2c05qa67h2h2drs3tvdph
  - &machine_macbook_m1 age10dd4t507h3ey68l2alu7z94s5lw0kshjq9lre5sv2vehrm9hg4rqk2let7
  - &nki_pc age1tt0peqg8zdfh74m5sdgwsczcqh036nhgmwvkqnvywll88uvmm9xs433rhm
  - &nkagami_main age1n8tnmmgredzltzwkspag7aufhrn6034ny8ysjeulhkwdnf7vqqaqec4mg5
  - &nkagami_do age1z2h24mjt80fryqupajkh3kg5r4sjgw65uqy489xeqxhqj8u2a9fsm3ff36
  - &nki_yoga age1vhjhmxura35apu5zdwg5ur5r40xay45ld9szh07dy0ph9chgsu7shfm4h9
  - &nki_framework age188tgu3psvywk6shq85mk2q0jdjwd0tcswzwlwu5pa5n3pndx75dq090z59
creation_rules:
  - path_regex: kagami-air-m1/secrets\.yaml$
    key_groups:
    - age:
        - *admin_macbook_m1
        - *machine_macbook_m1
  - path_regex: nki-personal-do/secrets/secrets\.yaml$
    key_groups:
    - age:
        - *nki_pc
        - *nkagami_main
        - *nkagami_do
        - *nki_framework
  - path_regex: nki-home/secrets\.yaml$
    key_groups:
    - age:
        - *nki_pc
        - *nkagami_main
        - *nkagami_do
  - path_regex: nki-yoga-g8/secrets\.yaml$
    key_groups:
    - age:
        - *nki_yoga
        - age1axvjllyv2gutngwmp3pvp4xtq2gqneldaq2c4nrzmaye0uwmk9lqsealdv # The machine itself
  - path_regex: nki-framework/secrets\.yaml$
    key_groups:
    - age:
        - *nki_framework
        - age1vgh6kvee8lvxylm7z86fpl3xzjyjs4u3zdfkyf064rjvxk9fpumsew7n27 # The machine itself
