keys:
  # People
  - &nki age15mqdpdguwfmhn7qkcxdshnv6d3ycjjyaz8gfrwypkzyuvne4yqcs0uj0mp
  # Hosts
  - &nki_pc_host age1tt0peqg8zdfh74m5sdgwsczcqh036nhgmwvkqnvywll88uvmm9xs433rhm
  - &nkagami_main age1n8tnmmgredzltzwkspag7aufhrn6034ny8ysjeulhkwdnf7vqqaqec4mg5
  - &nki_yoga age1axvjllyv2gutngwmp3pvp4xtq2gqneldaq2c4nrzmaye0uwmk9lqsealdv
  - &nki_fw age1d9tkjv7enjm8nxde2xpd965urtuyq66jkmwd8y3jzqcrgqfawutqaj9386
creation_rules:
  - path_regex: nki-personal-do/secrets/secrets\.yaml$
    key_groups:
    - age:
        - *nki
        - *nkagami_main
  - path_regex: nki-home/secrets\.yaml$
    key_groups:
    - age:
        - *nki
        - *nki_pc_host
  - path_regex: nki-yoga-g8/secrets\.yaml$
    key_groups:
    - age:
        - *nki
        - *nki_yoga
  - path_regex: nki-framework/secrets\.yaml$
    key_groups:
    - age:
        - *nki
        - *nki_fw
