{
  pkgs,
  lib,
  config,
  ...
}:
let
  cfg = config.programs.my-niri.dms;
  filesToInclude = [
    # Files under `$XDG_CONFIG_HOME/niri/dms` to be included into the new config
    "alttab" # Please note that niri will throw an error if any of these files are missing.
    "binds"
    "colors"
    "cursor"
    "layout"
    "outputs"
    "wpblur"
  ];

  createFilesToInclude =
    let
      configDir = "~/.config/niri/dms";
      paths = builtins.map (f: "${configDir}/${f}.kdl") filesToInclude;
    in
    pkgs.writeShellScript "niri-dms-create" ''
      mkdir -p ${configDir}
      touch ${lib.concatStringsSep " " paths}
    '';
in
{
  options.programs.my-niri.dms = {
    backlight-device = lib.mkOption { type = lib.types.str; };
    keyboard-backlight-device = lib.mkOption {
      type = lib.types.nullOr lib.types.str;
      default = null;
    };
  };
  config = lib.mkIf config.programs.my-niri.enable {
    systemd.user.services.niri-dms-setup = {
      Service.Type = "oneshot";
      Service.ExecStart = createFilesToInclude;
      Install.WantedBy = [ "niri.service" ];
      Unit.Before = [ "niri.service" ];
    };
    programs.niri.settings.binds =
      with config.lib.niri.actions;
      {
        "Mod+Shift+Comma" = {
          hotkey-overlay.title = "Settings";
          action = spawn "dms" "ipc" "call" "settings" "focusOrToggle";
        };
        "Mod+M" = {
          hotkey-overlay.title = "Task Manager";
          action = spawn "dms" "ipc" "call" "processlist" "focusOrToggle";
        };
        "Mod+N" = {
          hotkey-overlay.title = "Notification Center";
          action = spawn "dms" "ipc" "call" "notifications" "toggle";
        };
        "Mod+Space" = {
          hotkey-overlay.title = "Application Launcher";
          action = spawn "dms" "ipc" "call" "spotlight" "toggle";
        };
        "Mod+Shift+V" = {
          hotkey-overlay.title = "Clipboard Manager";
          action = spawn "dms" "ipc" "call" "clipboard" "toggle";
        };
        "Mod+Y" = {
          hotkey-overlay.title = "Browse Wallpapers";
          action = spawn "dms" "ipc" "call" "dankdash" "wallpaper";
        };
        "Mod+Semicolon" = {
          hotkey-overlay.title = "Lock Screen";
          action = spawn "dms" "ipc" "call" "lock" "lock";
        };
        "XF86AudioLowerVolume" = {
          allow-when-locked = true;
          action = spawn "dms" "ipc" "call" "audio" "decrement" "3";
        };
        "XF86AudioMute" = {
          allow-when-locked = true;
          action = spawn "dms" "ipc" "call" "audio" "mute";
        };
        "XF86AudioRaiseVolume" = {
          allow-when-locked = true;
          action = spawn "dms" "ipc" "call" "audio" "increment" "3";
        };
        "XF86MonBrightnessDown" = {
          allow-when-locked = true;
          action = spawn "dms" "ipc" "call" "brightness" "decrement" "5" cfg.backlight-device;
        };
        "XF86MonBrightnessUp" = {
          allow-when-locked = true;
          action = spawn "dms" "ipc" "call" "brightness" "increment" "5" cfg.backlight-device;
        };
      }
      // lib.optionalAttrs (cfg.keyboard-backlight-device != null) {
        "Shift+XF86MonBrightnessDown" = {
          allow-when-locked = true;
          action = spawn "dms" "ipc" "call" "brightness" "decrement" "5" cfg.keyboard-backlight-device;
        };
        "Shift+XF86MonBrightnessUp" = {
          allow-when-locked = true;
          action = spawn "dms" "ipc" "call" "brightness" "increment" "5" cfg.keyboard-backlight-device;
        };
      };

    systemd.user.services.dms.Install.WantedBy = lib.mkForce [ "niri.service" ];
    systemd.user.services.dms.Unit.After = [ "niri.service" ];

    # Enable dynamic theming
    programs.kitty.settings.extraConfig = ''
      include dank-tabs.conf
      include dank-theme.conf
    '';

    programs.dank-material-shell = {
      enable = true;
      systemd = {
        enable = true;
        restartIfChanged = true;
      };
      niri.includes = {
        enable = true; # Enable config includes hack.
        override = true; # If disabled, DMS settings won't be prioritized over settings defined using niri-flake
        originalFileName = "hm"; # A new name (without extension) for the config file generated by niri-flake.
        inherit filesToInclude;
      };

      # Core features
      enableSystemMonitoring = true; # System monitoring widgets (dgop)
      enableDynamicTheming = true; # Wallpaper-based theming (matugen)
      enableAudioWavelength = true; # Audio visualizer (cava)
      enableCalendarEvents = true; # Calendar integration (khal)

      settings = {
        currentThemeName = "dynamic";
        currentThemeCategory = "dynamic";
        customThemeFile = "";
        registryThemeVariants = { };
        matugenScheme = "scheme-vibrant";
        runUserMatugenTemplates = true;
        matugenTargetMonitor = "";
        popupTransparency = 1;
        dockTransparency = 1;
        widgetBackgroundColor = "sch";
        widgetColorMode = "default";
        cornerRadius = 12;
        niriLayoutGapsOverride = 8;
        niriLayoutRadiusOverride = -1;
        use24HourClock = true;
        showSeconds = false;
        useFahrenheit = false;
        nightModeEnabled = false;
        animationSpeed = 1;
        customAnimationDuration = 500;
        wallpaperFillMode = "Fill";
        blurredWallpaperLayer = true;
        blurWallpaperOnOverview = true;
        showLauncherButton = true;
        showWorkspaceSwitcher = true;
        showFocusedWindow = true;
        showWeather = true;
        showMusic = true;
        showClipboard = true;
        showCpuUsage = true;
        showMemUsage = true;
        showCpuTemp = true;
        showGpuTemp = true;
        selectedGpuIndex = 0;
        enabledGpuPciIds = [ ];
        showSystemTray = true;
        showClock = true;
        showNotificationButton = true;
        showBattery = true;
        showControlCenterButton = true;
        showCapsLockIndicator = true;
        controlCenterShowNetworkIcon = true;
        controlCenterShowBluetoothIcon = true;
        controlCenterShowAudioIcon = true;
        controlCenterShowAudioPercent = false;
        controlCenterShowVpnIcon = true;
        controlCenterShowBrightnessIcon = false;
        controlCenterShowBrightnessPercent = false;
        controlCenterShowMicIcon = false;
        controlCenterShowMicPercent = true;
        controlCenterShowBatteryIcon = false;
        controlCenterShowPrinterIcon = false;
        showPrivacyButton = true;
        privacyShowMicIcon = false;
        privacyShowCameraIcon = false;
        privacyShowScreenShareIcon = false;
        controlCenterWidgets = [
          {
            id = "volumeSlider";
            enabled = true;
            width = 50;
          }
          {
            id = "brightnessSlider";
            enabled = true;
            width = 50;
          }
          {
            id = "wifi";
            enabled = true;
            width = 50;
          }
          {
            id = "bluetooth";
            enabled = true;
            width = 50;
          }
          {
            id = "audioOutput";
            enabled = true;
            width = 50;
          }
          {
            id = "audioInput";
            enabled = true;
            width = 50;
          }
          {
            id = "nightMode";
            enabled = true;
            width = 50;
          }
          {
            id = "darkMode";
            enabled = true;
            width = 50;
          }
        ];
        showWorkspaceIndex = false;
        showWorkspaceName = false;
        showWorkspacePadding = false;
        workspaceScrolling = false;
        showWorkspaceApps = true;
        maxWorkspaceIcons = 3;
        groupWorkspaceApps = true;
        workspacesPerMonitor = true;
        showOccupiedWorkspacesOnly = false;
        reverseScrolling = false;
        dwlShowAllTags = false;
        workspaceNameIcons = { };
        waveProgressEnabled = true;
        scrollTitleEnabled = true;
        audioVisualizerEnabled = true;
        audioScrollMode = "volume";
        clockCompactMode = false;
        focusedWindowCompactMode = false;
        runningAppsCompactMode = true;
        keyboardLayoutNameCompactMode = false;
        runningAppsCurrentWorkspace = false;
        runningAppsGroupByApp = false;
        centeringMode = "index";
        clockDateFormat = "";
        lockDateFormat = "";
        mediaSize = 1;
        appLauncherViewMode = "list";
        spotlightModalViewMode = "list";
        sortAppsAlphabetically = false;
        appLauncherGridColumns = 4;
        spotlightCloseNiriOverview = true;
        niriOverviewOverlayEnabled = true;
        useAutoLocation = true;
        weatherEnabled = true;
        networkPreference = "auto";
        vpnLastConnected = "";
        iconTheme = "System Default";
        launcherLogoMode = "apps";
        launcherLogoCustomPath = "";
        launcherLogoColorOverride = "";
        launcherLogoColorInvertOnMode = false;
        launcherLogoBrightness = 0.5;
        launcherLogoContrast = 1;
        launcherLogoSizeOffset = 0;
        fontFamily = "Inter Variable";
        monoFontFamily = "Fantasque Sans Mono";
        fontWeight = 400;
        fontScale = 1;
        notepadUseMonospace = true;
        notepadFontFamily = "";
        notepadFontSize = 14;
        notepadShowLineNumbers = false;
        notepadTransparencyOverride = -1;
        notepadLastCustomTransparency = 0.7;
        soundsEnabled = true;
        useSystemSoundTheme = false;
        soundNewNotification = true;
        soundVolumeChanged = true;
        soundPluggedIn = true;
        acMonitorTimeout = 0;
        acLockTimeout = 900;
        acSuspendTimeout = 0;
        acSuspendBehavior = 0;
        acProfileName = "";
        batteryMonitorTimeout = 0;
        batteryLockTimeout = 900;
        batterySuspendTimeout = 1800;
        batterySuspendBehavior = 2;
        batteryProfileName = "0";
        batteryChargeLimit = 80;
        lockBeforeSuspend = true;
        loginctlLockIntegration = true;
        fadeToLockEnabled = true;
        fadeToLockGracePeriod = 5;
        fadeToDpmsEnabled = false;
        fadeToDpmsGracePeriod = 5;
        launchPrefix = "";
        brightnessDevicePins = { };
        wifiNetworkPins = { };
        bluetoothDevicePins = { };
        audioInputDevicePins = { };
        audioOutputDevicePins = { };
        gtkThemingEnabled = false;
        qtThemingEnabled = false;
        syncModeWithPortal = true;
        terminalsAlwaysDark = false;
        runDmsMatugenTemplates = true;
        matugenTemplateGtk = true;
        matugenTemplateNiri = true;
        matugenTemplateQt5ct = true;
        matugenTemplateQt6ct = true;
        matugenTemplateFirefox = true;
        matugenTemplatePywalfox = true;
        matugenTemplateZenBrowser = true;
        matugenTemplateVesktop = true;
        matugenTemplateEquibop = true;
        matugenTemplateGhostty = true;
        matugenTemplateKitty = true;
        matugenTemplateFoot = true;
        matugenTemplateAlacritty = true;
        matugenTemplateNeovim = true;
        matugenTemplateWezterm = true;
        matugenTemplateDgop = true;
        matugenTemplateKcolorscheme = true;
        matugenTemplateVscode = true;
        showDock = false;
        dockAutoHide = false;
        dockGroupByApp = false;
        dockOpenOnOverview = true;
        dockPosition = 1;
        dockSpacing = 4;
        dockBottomGap = 0;
        dockMargin = 0;
        dockIconSize = 40;
        dockIndicatorStyle = "circle";
        dockBorderEnabled = false;
        dockBorderColor = "surfaceText";
        dockBorderOpacity = 1;
        dockBorderThickness = 1;
        dockIsolateDisplays = false;
        notificationOverlayEnabled = false;
        modalDarkenBackground = true;
        lockScreenShowPowerActions = true;
        lockScreenShowSystemIcons = true;
        lockScreenShowTime = true;
        lockScreenShowDate = true;
        lockScreenShowProfileImage = true;
        lockScreenShowPasswordField = true;
        enableFprint = false;
        maxFprintTries = 15;
        lockScreenActiveMonitor = "all";
        lockScreenInactiveColor = "#000000";
        hideBrightnessSlider = false;
        notificationTimeoutLow = 5000;
        notificationTimeoutNormal = 5000;
        notificationTimeoutCritical = 0;
        notificationPopupPosition = 0;
        notificationHistoryEnabled = true;
        notificationHistoryMaxCount = 50;
        notificationHistoryMaxAgeDays = 7;
        notificationHistorySaveLow = true;
        notificationHistorySaveNormal = true;
        notificationHistorySaveCritical = true;
        osdAlwaysShowValue = false;
        osdPosition = 5;
        osdVolumeEnabled = true;
        osdMediaVolumeEnabled = true;
        osdBrightnessEnabled = true;
        osdIdleInhibitorEnabled = true;
        osdMicMuteEnabled = true;
        osdCapsLockEnabled = true;
        osdPowerProfileEnabled = true;
        osdAudioOutputEnabled = true;
        powerActionConfirm = true;
        powerActionHoldDuration = 0.5;
        powerMenuActions = [
          "reboot"
          "logout"
          "poweroff"
          "lock"
          "suspend"
          "restart"
        ];
        powerMenuDefaultAction = "poweroff";
        powerMenuGridLayout = false;
        customPowerActionLock = "";
        customPowerActionLogout = "";
        customPowerActionSuspend = "";
        customPowerActionHibernate = "";
        customPowerActionReboot = "";
        customPowerActionPowerOff = "";
        updaterHideWidget = false;
        updaterUseCustomCommand = false;
        updaterCustomCommand = "";
        updaterTerminalAdditionalParams = "";
        displayNameMode = "system";
        screenPreferences = { };
        showOnLastDisplay = { };
        niriOutputSettings = { };
        hyprlandOutputSettings = { };
        barConfigs = [
          {
            id = "default";
            name = "Main Bar";
            enabled = true;
            position = 2;
            screenPreferences = [
              "all"
            ];
            showOnLastDisplay = true;
            leftWidgets = [
              "launcherButton"
              "workspaceSwitcher"
              "focusedWindow"
            ];
            centerWidgets = [
              "music"
              "clock"
              "weather"
            ];
            rightWidgets = [
              "systemTray"
              "clipboard"
              "cpuUsage"
              "memUsage"
              "notificationButton"
              "battery"
              {
                id = "controlCenterButton";
                enabled = true;
                showNetworkIcon = true;
                showBluetoothIcon = true;
                showAudioIcon = true;
                showAudioPercent = false;
                showVpnIcon = true;
                showBrightnessIcon = false;
                showBrightnessPercent = false;
                showMicIcon = false;
                showMicPercent = true;
                showBatteryIcon = false;
                showPrinterIcon = false;
              }
            ];
            spacing = 0;
            innerPadding = 8;
            bottomGap = 0;
            transparency = 0.85;
            widgetTransparency = 1;
            squareCorners = true;
            noBackground = false;
            gothCornersEnabled = true;
            gothCornerRadiusOverride = false;
            gothCornerRadiusValue = 12;
            borderEnabled = false;
            borderColor = "surfaceText";
            borderOpacity = 1;
            borderThickness = 1;
            widgetOutlineEnabled = false;
            widgetOutlineColor = "primary";
            widgetOutlineOpacity = 1;
            widgetOutlineThickness = 1;
            fontScale = 1;
            autoHide = false;
            autoHideDelay = 250;
            showOnWindowsOpen = false;
            openOnOverview = false;
            visible = true;
            popupGapsAuto = true;
            popupGapsManual = 4;
            maximizeDetection = true;
            scrollEnabled = true;
            scrollXBehavior = "column";
            scrollYBehavior = "workspace";
          }
        ];
        desktopClockEnabled = false;
        desktopClockStyle = "analog";
        desktopClockTransparency = 0.8;
        desktopClockColorMode = "primary";
        desktopClockCustomColor = {
          r = 1;
          g = 1;
          b = 1;
          a = 1;
          hsvHue = -1;
          hsvSaturation = 0;
          hsvValue = 1;
          hslHue = -1;
          hslSaturation = 0;
          hslLightness = 1;
          valid = true;
        };
        desktopClockShowDate = true;
        desktopClockShowAnalogNumbers = false;
        desktopClockShowAnalogSeconds = true;
        desktopClockX = -1;
        desktopClockY = -1;
        desktopClockWidth = 280;
        desktopClockHeight = 180;
        desktopClockDisplayPreferences = [
          "all"
        ];
        systemMonitorEnabled = false;
        systemMonitorShowHeader = true;
        systemMonitorTransparency = 0.8;
        systemMonitorColorMode = "primary";
        systemMonitorCustomColor = {
          r = 1;
          g = 1;
          b = 1;
          a = 1;
          hsvHue = -1;
          hsvSaturation = 0;
          hsvValue = 1;
          hslHue = -1;
          hslSaturation = 0;
          hslLightness = 1;
          valid = true;
        };
        systemMonitorShowCpu = true;
        systemMonitorShowCpuGraph = true;
        systemMonitorShowCpuTemp = true;
        systemMonitorShowGpuTemp = false;
        systemMonitorGpuPciId = "";
        systemMonitorShowMemory = true;
        systemMonitorShowMemoryGraph = true;
        systemMonitorShowNetwork = true;
        systemMonitorShowNetworkGraph = true;
        systemMonitorShowDisk = true;
        systemMonitorShowTopProcesses = false;
        systemMonitorTopProcessCount = 3;
        systemMonitorTopProcessSortBy = "cpu";
        systemMonitorGraphInterval = 60;
        systemMonitorLayoutMode = "auto";
        systemMonitorX = -1;
        systemMonitorY = -1;
        systemMonitorWidth = 320;
        systemMonitorHeight = 480;
        systemMonitorDisplayPreferences = [
          "all"
        ];
        systemMonitorVariants = [ ];
        desktopWidgetPositions = { };
        desktopWidgetGridSettings = { };
        desktopWidgetInstances = [ ];
        configVersion = 5;
      };
    };
  };
}
