# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/ed6ef17f-4ad2-48ef-99bb-c4c9d12d6646";
      fsType = "btrfs";
      options = [ "subvol=root" ];
    };
  services.btrfs.autoScrub = {
    enable = true;
    interval = "monthly";
  };

  common.linux.luksDevices."cryptroot" = "/dev/disk/by-uuid/c676ec99-31d2-420a-af19-a25c4766d87c";

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/ed6ef17f-4ad2-48ef-99bb-c4c9d12d6646";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/ed6ef17f-4ad2-48ef-99bb-c4c9d12d6646";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/4843-028F";
      fsType = "vfat";
    };

  swapDevices = [
    { device = "/var/swapfile"; size = 32 * 1024; priority = 10; }
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp1s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  # Fingerprint
  services.fprintd.enable = true;

  hardware.sensor.iio.enable = true; # Orientaion and ambient light sensors
}
