# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:
let
  btrfs-subvol = name: {
    device = "/dev/mapper/root";
    fsType = "btrfs";
    options = [
      "subvol=${name}"
      "compress=zstd"
    ];
  };
in
{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "thunderbolt"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.kernelParams = [
    # Hibernation
    # "resume=UUID=cf280463-b8cb-4e5d-bff3-973068a2c8d5"
    # "resume_offset=7349504" # btrfs inspect-internal map-swapfile -r /var/swapfile
  ];

  fileSystems."/" = btrfs-subvol "nixos";
  services.btrfs.autoScrub = {
    enable = true;
    interval = "monthly";
  };

  common.linux.luksDevices."root" = "/dev/disk/by-uuid/091ea01b-2074-48bc-911a-12362fd6f1c7";

  fileSystems."/home" = btrfs-subvol "nixos/home";
  fileSystems."/nix" = btrfs-subvol "nix";
  fileSystems."/swap" = btrfs-subvol "nixos/swap";
  fileSystems."/home/nki/Projects" = btrfs-subvol "projects";
  fileSystems."/var/steam" = btrfs-subvol "steam";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/6A0E-4D23";
    fsType = "vfat";
  };

  swapDevices = [
    {
      device = "/swap/swapfile";
      size = 32 * 1024;
      priority = 10;
    }
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp1s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  environment.systemPackages = with pkgs; [ vulkan-validation-layers ];

  # Fingerprint
  services.fprintd.enable = true;

  hardware.sensor.iio.enable = true; # Orientaion and ambient light sensors

  # Fans

  hardware.fw-fanctrl.enable = true;
}
