#!/usr/bin/env fish

function usage
    echo "Usage: "
    echo "  kaktex set [client] [session]"
    echo "  kaktex jump [file] [line]"
    exit 1
end

if test (count $argv) -ne 3
    usage
end

switch $argv[1]
    case "set"
        set -U _kaktex_client $argv[2]
        set -U _kaktex_session $argv[3]
    case "jump"
        echo "
                 evaluate-commands -client $_kaktex_client %{
                     evaluate-commands -try-client $_kaktex_client %{
                         edit -- $argv[2] $argv[3]
                     }
                 }
             " | kak -p $_kaktex_session
    case '*'
        usage
end
