# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  lib,
  pkgs,
  modulesPath,
  ...
}:

let
  from-encdata = subvol: {
    device = "/dev/disk/by-uuid/d1db9f65-6add-4714-b9d7-16e16f687396";
    fsType = "btrfs";
    options = [
      "compress=zstd"
      "subvol=${subvol}"
    ];
    encrypted = {
      enable = true;
      label = "encdata";
      blkDev = "/dev/disk/by-uuid/6544f506-9a22-479c-8bfc-aee1b9e0deda";
      keyFile = "/sysroot/var/crypto/key_data";
    };
  };

  immich-volume =
    {
      label,
      device,
      blkDev,
    }:
    {
      inherit device;
      fsType = "btrfs";
      options = [ "compress=zstd" ];
      encrypted = {
        inherit label blkDev;
        enable = true;
        keyFile = "/sysroot/var/crypto/immich_key";
      };
    };

in
{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
    ./audio
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "ahci"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [
    "dm-snapshot"
    "amdgpu"
  ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.kernelPatches = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/32a74827-4624-43ef-b066-b52e1f11793d";
    fsType = "ext4";
  };
  fileSystems."/home/nki/Projects" = {
    device = "/dev/disk/by-uuid/025cb533-e21b-47f2-b7d5-322b7b95b831";
    fsType = "btrfs";
    options = [ "compress=zstd" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/549C-7877";
    fsType = "vfat";
  };

  fileSystems."/mnt/steam" = from-encdata "steam";
  fileSystems."/nix" = from-encdata "nix";
  fileSystems."/mnt/immich" = immich-volume {
    device = "/dev/disk/by-uuid/f7b57fe0-45c8-44a4-9b01-165dd8fb95b1";
    blkDev = "/dev/disk/by-uuid/9f4fec04-1b02-4b6a-9eb1-5b4e18082de0";
    label = "immich";
  };
  fileSystems."/mnt/immich-backup" = immich-volume {
    device = "/dev/disk/by-uuid/3f7ee402-fc66-43d5-9bda-a0a1a93ec496";
    blkDev = "/dev/disk/by-uuid/d6f584db-3cb5-49f4-a55f-28e5a2075d6a";
    label = "immich-backup";
  };

  swapDevices = [ { device = "/dev/disk/by-uuid/561f6441-1915-4059-a5e1-76a449b0c9bf"; } ];

  # bluetooth usb
  hardware.firmware = [ pkgs.rtl8761b-firmware ];

  nixpkgs.config.rocmSupport = true;
}
