# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ "dm-snapshot" "amdgpu" ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/32a74827-4624-43ef-b066-b52e1f11793d";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/549C-7877";
      fsType = "vfat";
    };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/561f6441-1915-4059-a5e1-76a449b0c9bf"; }];

  # high-resolution display
  hardware.video.hidpi.enable = lib.mkDefault true;

  # GPU options
  services.xserver.videoDrivers = [ "amdgpu" ];
  hardware.opengl.enable = true;

  # bluetooth usb
  hardware.firmware = [ pkgs.rtl8761b-firmware ];
}
