name: "Deploy to nki-personal"
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
    types:
    - opened
    - synchronize
    - reopened
    - labeled
jobs:
  deploy:
    if: "github.event.name == 'push' || contains(github.event.pull_request.labels.*.name, 'Deploy')"
    runs-on: ubuntu-latest
    name: Deploy
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v14.1
      with:
        extra_nix_config: |
          experimental-features = nix-command flakes
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - name: Add SSH key
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
        mkdir -p /home/runner/.ssh
        # Replace example.com with the hostname of the machine
        # you're SSH-ing into
        ssh-keyscan ${{ secrets.INSTANCE_IP }} >> /home/runner/.ssh/known_hosts
        # DOKKU_SSH_KEY is the name of the repository secret
        echo "${{ secrets.SSH_KEY }}" > /home/runner/.ssh/github_actions
        chmod 600 /home/runner/.ssh/github_actions
        ssh-agent -a $SSH_AUTH_SOCK > /dev/null   
        ssh-add /home/runner/.ssh/github_actions
    - name: Deploy with deploy-rs
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
        nix run github:Serokell/deploy-rs . -- --hostname ${{ secrets.INSTANCE_IP }}
