name: "Deploy to nki-personal"
on:
  push: master
  pull_request:
jobs:
  deploy:
    if: "github.event.name == 'push' || contains(github.event.pull_request.labels.*.name, 'Deploy')"
    runs-on: ubuntu-latest
    name: Deploy
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v14.1
      with:
        install_url: https://nixos-nix-install-tests.cachix.org/serve/kqchxcar98r8hj447mz0c0fdvdi5xcw1/install
        install_options: '--tarball-url-prefix https://nixos-nix-install-tests.cachix.org/serve'
        extra_nix_config: |
          experimental-features = nix-command flakes
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - name: Open Firewall for Deployment
      uses: digitalocean/actiond-doctl@v2.1.0
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      run: |
        doctl compute firewall add-rules ${{ secrets.INSTANCE_FIREWALL }} --inbound-rules protocol:tcp,ports:22,address:${curl -L https://api.ipify.org}
    - name: Deploy with deploy-rs
      working-directory: ./nki-personal-do
      run: |
        nix run github:Serokell/deploy-rs . -- --hostname ${{ env.INSTANCE_IP }}
    - name: Close Firewall for Deployment
      uses: digitalocean/actiond-doctl@v2.1.0
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      run: |
        doctl compute firewall remove-rules ${{ secrets.INSTANCE_FIREWALL }} --inbound-rules protocol:tcp,ports:22,address:${curl -L https://api.ipify.org}
